apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-be
  labels:
    {{- include "rasa-bot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rasa-bot.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "rasa-bot.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          {{- with .Values.backend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 8000
              name: http
          {{- with .Values.backend.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
          {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.database }}
            - name: DATABASE_NAME
              value: "{{ .name }}"
            - name: DATABASE_USER
              value: "{{ .user }}"
            - name: DATABASE_PASSWORD
              value: "{{ .password }}"
            - name: DATABASE_HOST
              value: "{{ .host }}"
            - name: DATABASE_PORT
              value: "{{ .port }}"
          {{- end }}
        
      volumes:
        - name: configmap
          configMap:
            name: {{ include "rasa-bot.fullname" . }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
