apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "rasa-bot.fullname" . }}
  labels:
    {{- include "rasa-bot.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt-prod
    networking.gke.io/managed-certificates: {{ include "rasa-bot.fullname" . }}
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    secretName: {{ include "rasa-bot.fullname" . }}-tls
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
        - path: /socket.io/
          backend:
            serviceName: {{ include "rasa-bot.fullname" . }}
            servicePort: rasa-api
        - path: /webhooks/
          backend:
            serviceName: {{ include "rasa-bot.fullname" . }}
            servicePort: rasa-api
        - backend:
            serviceName: {{ .Release.Name }}-be
            servicePort: http
