apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: {{ include "rasa-bot.fullname" . }}
  labels:
    {{- include "rasa-bot.labels" . | nindent 4 }}
spec:
  domains:
    - {{ .Values.ingress.hostname }}
